version: '3.3'

#Docker Networks
networks:
  app-network:
    driver: bridge

services:

  #Application
  app:
    container_name: ${APP_NAME}_app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    working_dir: /var/www
    restart: on-failure
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  #NGINX
  web:
    image: nginx:1.17
    container_name: ${APP_NAME}_web
    tty: true
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network
